### ISSUE TITLE
server chan use new api

### ISSUE THREAD

**Issue by peixin** [yakumioto/serverchan-action#2]
[因为微信发布公告将在4月底下线模板消息，Server酱开发了以企业微信为主的多通道新版（ Turbo版 sct.ftqq.com ）。旧版将在4月后下线，请尽快完成配置的更新。](http://sc.ftqq.com/9.version)

```
post https://sctapi.ftqq.com/****************.send

参数说明如下：
title: 消息标题，必填。最大长度为 32 。
desp: 消息内容，选填。支持 Markdown语法 ，最大长度为 32KB ,消息卡片截取前 30 显示。
openid: 选填。抄送给其他关注你测试号的 openid ，多个 openid 用 , 隔开。

```

**Comment by peixin** [comment]
PR: https://github.com/yakumioto/serverchan-action/pull/3

**Comment by yakumioto** [comment]
Supported in 325a1699b2f6016a0931f18af2baede1900a6c29 commit.
